# Generated by Django 6.0.4 on 2026-05-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='perfiles_extra', to='usuarios.rol'),
        ),
    ]
